### ISSUE TITLE
Should the api provide ways to interact directly with minecraft?

### ISSUE THREAD

**Issue by cout970** [Darkaqua/Blacksmith-Api#3]
Should the api add a way to get an IItemStack from an ItemStack and vice versa?  If the api adds this possibility then the modder must control their access to minecraft to be able to work in different versions, but allow to use utilities in minecraft that the api don't have yet.

**Comment by Cypher121** [comment]
Absolutely yes, otherwise it would be impossible for other mods to interact with BS-based classes adequately without depending on BS themselves.
